return {
	{
		"nvim-treesitter/nvim-treesitter",
		dependencies = {
			"nvim-treesitter/nvim-treesitter-textobjects",
		},
		opts = {
			highlight = { enable = true },
			indent = { enable = true },
			ensure_installed = {
				"bash",
				"c",
				"c_sharp",
				"clojure",
				"cmake",
				"comment",
				"cpp",
				"css",
				"csv",
				"dart",
				"dockerfile",
				"elixir",
				"elm",
				"erlang",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"gleam",
				"glsl",
				"go",
        "gdscript",
				"graphql",
				"html",
				"hjson",
				"hlsl",
				"http",
				"hocon",
				"ini",
				"java",
				"javascript",
				"jq",
				"jsdoc",
				"json",
				"json5",
				"kotlin",
				"latex",
				"lua",
				"luadoc",
				"luap",
				"make",
				"markdown",
				"markdown_inline",
        "nix",
				"ocaml",
				"ocaml_interface",
				"python",
				"prisma",
				"query",
				"r",
				"roc",
				"regex",
				"ruby",
				"rust",
				"scss",
				"scala",
				"sql",
				"svelte",
				"swift",
				"toml",
				"tsx",
				"typescript",
				"vim",
				"vimdoc",
				"xml",
				"yaml",
				"zig",
			},
			incremental_selection = {
				enable = true,
				keymaps = {
					init_selection = "<C-space>",
					node_incremental = "<C-space>",
					scope_incremental = false,
					node_decremental = "<bs>",
				},
			},
		},
	},
	{
		"nvim-treesitter/nvim-treesitter-context",
	},
}
